import { analyzeEmailAndJobRisk, callOpenAI } from '../services/aiService.js';

// @desc    Analyze recruiter or job email for category, dates & scam risk
// @route   POST /api/email-guardian/analyze
// @access  Private
export const analyzeEmail = async (req, res, next) => {
  try {
    const { emailText, senderEmail, subject } = req.body;

    if (!emailText || emailText.trim() === '') {
      return res.status(400).json({
        success: false,
        message: 'Please provide email body text to analyze.'
      });
    }

    const fullContent = `${subject ? `Subject: ${subject}\n` : ''}${senderEmail ? `From: ${senderEmail}\n` : ''}\n${emailText}`;
    const fallbackAssessment = analyzeEmailAndJobRisk(fullContent);

    // If sender email is provided, check domain
    if (senderEmail) {
      const freeProviders = ['@gmail.com', '@yahoo.com', '@hotmail.com', '@outlook.com', '@aol.com'];
      const isFreeDomain = freeProviders.some(domain => senderEmail.toLowerCase().includes(domain));
      if (isFreeDomain && !fallbackAssessment.signals.some(s => s.message.includes('personal email'))) {
        fallbackAssessment.signals.push({
          type: 'warning',
          message: `Sender is using a generic webmail address (${senderEmail}) rather than an official corporate domain.`
        });
        fallbackAssessment.riskScore = Math.min(fallbackAssessment.riskScore + 15, 100);
        if (fallbackAssessment.riskScore >= 60) fallbackAssessment.riskLevel = 'High Risk';
        else if (fallbackAssessment.riskScore >= 30) fallbackAssessment.riskLevel = 'Medium Risk';
      }
    }

    // Try OpenAI if configured
    const messages = [
      {
        role: 'system',
        content: `You are an expert recruitment security specialist. Analyze this job-related communication. Return strict JSON:
{
  "category": "Interview Invitation" | "Application Rejection" | "Offer Letter" | "Technical Assessment" | "Recruiter Outreach" | "Suspicious Opportunity",
  "riskLevel": "Low Risk" | "Medium Risk" | "High Risk",
  "riskScore": 15,
  "signals": [{"type": "warning" | "danger" | "info", "message": "..."}],
  "extractedDates": ["..."],
  "extractedLinks": ["..."],
  "recommendations": ["..."],
  "disclaimer": "This automated risk assessment is generated by Career Flow and is not a legal guarantee."
}`
      },
      {
        role: 'user',
        content: fullContent
      }
    ];

    const aiResult = await callOpenAI(messages, { json: true, max_tokens: 800 });
    let assessment = fallbackAssessment;

    if (aiResult) {
      try {
        assessment = JSON.parse(aiResult);
      } catch {
        assessment = fallbackAssessment;
      }
    }

    res.status(200).json({
      success: true,
      analysis: assessment
    });
  } catch (error) {
    next(error);
  }
};
